#####################################
# Langfuse Secrets
# These secrets are required for Langfuse to function
#####################################

#####################################
# NEXTAUTH_SECRET - Used for session cookie validation
#####################################
resource "aws_secretsmanager_secret" "nextauth_secret" {
  name        = "${var.name_prefix}-langfuse-nextauth-secret"
  description = "Langfuse NEXTAUTH_SECRET for session management"

  tags = {
    Name        = "${var.name_prefix}-langfuse-nextauth-secret"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "nextauth_secret" {
  secret_id     = aws_secretsmanager_secret.nextauth_secret.id
  secret_string = random_password.nextauth_secret.result
}

resource "random_password" "nextauth_secret" {
  length  = 32
  special = true
}

#####################################
# SALT - Used for API key hashing
#####################################
resource "aws_secretsmanager_secret" "salt" {
  name        = "${var.name_prefix}-langfuse-salt"
  description = "Langfuse SALT for API key hashing"

  tags = {
    Name        = "${var.name_prefix}-langfuse-salt"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "salt" {
  secret_id     = aws_secretsmanager_secret.salt.id
  secret_string = random_password.salt.result
}

resource "random_password" "salt" {
  length  = 32
  special = true
}

#####################################
# ENCRYPTION_KEY - Used for encrypting sensitive data
#####################################
resource "aws_secretsmanager_secret" "encryption_key" {
  name        = "${var.name_prefix}-langfuse-encryption-key"
  description = "Langfuse ENCRYPTION_KEY for sensitive data"

  tags = {
    Name        = "${var.name_prefix}-langfuse-encryption-key"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "encryption_key" {
  secret_id     = aws_secretsmanager_secret.encryption_key.id
  secret_string = random_password.encryption_key.result
}

resource "random_password" "encryption_key" {
  length  = 32
  special = false # Encryption keys should not have special characters
}

#####################################
# Langfuse Initial Project Keys
# These are auto-generated by Langfuse on first startup
# We create placeholders that will be populated by Langfuse
#####################################
resource "aws_secretsmanager_secret" "langfuse_init_project_secret_key" {
  name        = "${var.name_prefix}-langfuse-init-project-secret-key"
  description = "Langfuse initial project secret key (auto-generated)"

  tags = {
    Name        = "${var.name_prefix}-langfuse-init-project-secret-key"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "langfuse_init_project_secret_key" {
  secret_id     = aws_secretsmanager_secret.langfuse_init_project_secret_key.id
  secret_string = random_password.langfuse_init_project_secret_key.result
}

resource "random_password" "langfuse_init_project_secret_key" {
  length  = 32
  special = false
}

resource "aws_secretsmanager_secret" "langfuse_init_project_public_key" {
  name        = "${var.name_prefix}-langfuse-init-project-public-key"
  description = "Langfuse initial project public key (auto-generated)"

  tags = {
    Name        = "${var.name_prefix}-langfuse-init-project-public-key"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "langfuse_init_project_public_key" {
  secret_id     = aws_secretsmanager_secret.langfuse_init_project_public_key.id
  secret_string = random_password.langfuse_init_project_public_key.result
}

resource "random_password" "langfuse_init_project_public_key" {
  length  = 32
  special = false
}

#####################################
# ClickHouse Password Secret
#####################################
resource "aws_secretsmanager_secret" "clickhouse_password" {
  name        = "${var.name_prefix}-langfuse-clickhouse-password"
  description = "ClickHouse database password"

  tags = {
    Name        = "${var.name_prefix}-langfuse-clickhouse-password"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "clickhouse_password" {
  secret_id     = aws_secretsmanager_secret.clickhouse_password.id
  secret_string = random_password.clickhouse_password.result
}

resource "random_password" "clickhouse_password" {
  length  = 32
  special = true
}

#####################################
# RDS PostgreSQL Password Secret
#####################################
resource "aws_secretsmanager_secret" "db_password" {
  name        = "${var.name_prefix}-langfuse-db-password"
  description = "Aurora PostgreSQL master password"

  tags = {
    Name        = "${var.name_prefix}-langfuse-db-password"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "db_password" {
  secret_id     = aws_secretsmanager_secret.db_password.id
  secret_string = random_password.db_password.result
}

resource "random_password" "db_password" {
  length  = 32
  special = true
}

#####################################
# Langfuse Init User Password Secret
#####################################
resource "aws_secretsmanager_secret" "langfuse_init_user_password" {
  name        = "${var.name_prefix}-langfuse-init-user-password"
  description = "Langfuse initial user password for UI access"

  tags = {
    Name        = "${var.name_prefix}-langfuse-init-user-password"
    Environment = var.environment
  }
}

resource "aws_secretsmanager_secret_version" "langfuse_init_user_password" {
  secret_id     = aws_secretsmanager_secret.langfuse_init_user_password.id
  secret_string = random_password.langfuse_init_user_password.result
}

resource "random_password" "langfuse_init_user_password" {
  length  = 32
  special = true
}
